// Popular process misbehaving // by jkb
let POPULARITY_THRESHOLD = 500;
let MINIMUM_RARE_ACTION_COUNT = 2;
let NoisyActions = pack_array(
    "ProcessCreatedUsingWmiQuery",
    "NtAllocateVirtualMemoryApiCall",
    "NtProtectVirtualMemoryApiCall",
    "NamedPipeEvent",
    "PowerShellCommand"
);
// Base events
let DATA =
DeviceEvents
| where ActionType !in (NoisyActions)
| where InitiatingProcessAccountDomain == "ad" and isnotempty(InitiatingProcessFileName)
| project DeviceId, InitiatingProcessFileName, ActionType
| summarize count() by DeviceId, InitiatingProcessFileName, ActionType;
// Find popular processes
let POPULAR_PROCESSES =
    DATA
    | summarize count() by DeviceId, InitiatingProcessFileName      // More accurate way than
    | summarize DeviceCount = count() by InitiatingProcessFileName  // dcount(DeviceId, 4)
    | where DeviceCount > POPULARITY_THRESHOLD;
POPULAR_PROCESSES
| join kind=inner (
    DATA
    // Use these 2 lines for more accuracy
    | summarize by DeviceId, InitiatingProcessFileName, ActionType
    | summarize RareActionDeviceProcessCount = count() by InitiatingProcessFileName, ActionType
    // Or this line for faster execution
    //| summarize RareActionDeviceProcessCount = dcount(DeviceId, 4) by InitiatingProcessFileName, ActionType
    // Find ActionType:Process pair that happens only on single device
    | where RareActionDeviceProcessCount == 1
) on InitiatingProcessFileName
| join kind=inner (DATA)
    on ActionType, InitiatingProcessFileName
// Count rare actions per Device and Process
| summarize RareActionsCount = count(), Actions = make_set(ActionType) by InitiatingProcessFileName, DeviceId
| where RareActionsCount >= MINIMUM_RARE_ACTION_COUNT
| mv-expand Actions
| extend ActionType = tostring(Actions)
// Join with full events data for more details and alert generation purposes
| join kind=inner (DeviceEvents) on DeviceId, ActionType, InitiatingProcessFileName
| summarize arg_max(Timestamp, *), Actions = make_set(ActionType) by DeviceId, InitiatingProcessFileName
| project-away Actions
| project-rename Actions = Actions1
| project-reorder DeviceId, DeviceName, InitiatingProcessFileName, Timestamp, RareActionsCount, Actions
