DeviceNetworkEvents
| where ActionType == "ConnectionSuccess"
| where not(ipv4_is_in_any_range(RemoteIP, 
    "127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/16",
    "172.17.0.0/16", "172.18.0.0/16", "172.19.0.0/16", "172.20.0.0/16", "172.21.0.0/16", "172.22.0.0/16"
    "172.23.0.0/16", "172.24.0.0/16", "172.25.0.0/16", "172.26.0.0/16", "172.27.0.0/16", "172.28.0.0/16"
    "172.29.0.0/16", "172.30.0.0/16", "172.31.0.0/16", 
    "192.168.0.0/16"
    ))
| summarize ClassifiedPublic = countif(RemoteIPType == "Public"), 
    PublicButNotClassified = countif(RemoteIPType != "Public" and not(ipv4_is_private(RemoteIP)))
| extend PercentageMissed = round(100 * ((PublicButNotClassified / todouble(ClassifiedPublic + PublicButNotClassified))), 2)
